version: "2"

run:
  timeout: 3m
  modules-download-mode: vendor

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - govet

formatters:
  enable:
    - gofmt
