dist: xenial
os: linux
services:
  - docker
language: go

go:
  - 1.15.x

env:
  global:
    - GOFLAGS=-mod=vendor
    - GO111MODULE=on

install:
  - make tools
  - go mod vendor

jobs:
  fast_finish: true
  allow_failures:
    - go: tip
  include:
    - name: "Code Lint"
      script: make lint
    - name: "Code UnitTest"
      script: make test
    - stage: deploy
      script: skip
      before_deploy:
        - echo "$GPG_PRIVATE_KEY" | base64 -d | gpg --import --no-tty --batch --yes
      deploy:
        - provider: script
          edge: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
